SHARED_HEADER_MAPPING = {
    "player_id": "player_id",
    "player_name": "name",
    "pitches": "pitches",
    "total_pitches": "total_pitches",
    "pitch_percent": "pitch_percent",
    "bip": "BIP",
    "iso": "ISO",
    "babip": "BABIP",
    "obp": "OBP",
    "slg": "SLG",
    "woba": "wOBA",
    "xobp": "xOBP",
    "xslg": "xSLG",
    "xwoba": "xwOBA",
    "xba": "xAVG",
    "xbadiff": "xAVGdiff",
    "xobpdiff": "xOBPdiff",
    "xslgdiff": "xSLGdiff",
    "wobadiff": "wOBAdiff",
    "launch_speed": "exit_velo",
    "launch_angle": "launch_angle",
    "so": "K",
    "k_percent": "K%",
    "bb": "BB",
    "bb_percent": "BB%",
    "bbdist": "BBdist",
    "barrels_total": "barrels_total",
    "hardhit_percent": "hardhit_pct",
    "barrels_per_bbe_percent": "barrels_per_bbe_pct",
    "barrels_per_pa_percent": "barrels_per_pa_pct",
    "swing_miss_percent": "swing_miss_pct",
    "whiffs": "whiffs",
    "swings": "swings",
    "takes": "takes",
    "run_exp": "run_exp",
}

BATTER_HEADER_MAPPINGS = {
    **SHARED_HEADER_MAPPING,
    "velocity": "pitch_velo",
    "effective_speed": "percieved_velo",
    "hyper_speed": "adj_exit_velo",
    "batter_run_value_per_100": "batter_run_value_per_100",
    "bat_speed": "bat_speed",
    "swing_length": "swing_length",
    "attack_angle": "attack_angle",
    "attack_direction": "attack_dir",
    "swing_path_tilt": "swing_path_tilt",
    "rate_ideal_attack_angle": "rate_ideal_attack_angle",
}

PITCHER_HEADER_MAPPINGS = {
    **SHARED_HEADER_MAPPING,
    "spin_rate": "spin_rate",
    "velocity": "velo",
    "effective_speed": "percieved_velo",
    "eff_min_vel": "eff_min_vel",
    "release_extension": "release_extension",
    "pitcher_run_exp": "pitcher_run_exp",
    "run_exp": "run_exp",
    "api_break_z_with_gravity": "break_z",
    "api_break_z_induced": "induced_break_z",
    "api_break_x_arm": "break_x_arm_side",
    "api_break_x_batter_in": "break_x_batter_in",
    "hyper_speed": "adj_exit_velo",
    "release_pos_z": "release_pos_z",
    "release_pos_x": "release_pos_x",
    "pitcher_run_value_per_100": "pitcher_run_value_per_100",
    "arm_angle": "arm_angle",
    "rate_ideal_attack_angle": "rate_ideal_attack_angle",
}
